# on:
#   push:
#     branches:
#       - main
# name: release-please
# jobs:
#   release-please:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: GoogleCloudPlatform/release-please-action@v1.5.0
#         with:
#           token: ${{ secrets.RELEASE_PR_TOKEN }}
#           release-type: node
#           package-name: release-please-action
